// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejdzofeyrjteiedzghtw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqZHpvZmV5cmp0ZWllZHpnaHR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNTM4MjksImV4cCI6MjA2NjYyOTgyOX0.gXnkL4H492jy_gtSPxMXyrSG1O9G8rT_JggeILkRz28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);